Algoritmo "oprelacionaisteste"

Var
 a, b, c : inteiro


Inicio
   a <- 2
   b <- 3
   c <- 5
   escreval(Verdadeiro e falso)
   escreval((a=b) ou (c>a))
   escreval(nao(a=b) ou (c>a))
   
   
   escreval("Ordem de precedebcia")
   escreval("1º - Lugar -> Aritméticos")
   escreval("2º - lugar -> Relacionais executados da esquerda para a direita")
   escreval("3º Lugar -> Lógicos")
   escreval("               E")
   escreval("              OU")
   escreval("             NAO")
   

Fimalgoritmo