Algoritmo "alunoReprovAprova"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 21/05/2020
Var
// Seção de Declarações das variáveis 


Inicio
// --------------
//Nome da escola
// Pede duas notas de 0 a 10
// Media de 7 para aprovacao


Fimalgoritmo