Algoritmo "condicionaiaAninhadas"

Var
   dinheiro : real

Inicio
      escreva("Quanto dinheiro juntou R$:")
      leia(dinheiro)
      se (dinheiro>=10000)entao
         escreval("Partiu Disney")
      senao
           se (dinheiro>=5000)entao
              escreval("Visitar a minha familia.")
            senao
                 escreval("Fica em casa")
            fimse
       fimse

Fimalgoritmo