Algoritmo "conversordemoedas"

Var
  Reais, dolar:real
  contador : inteiro


Inicio
    contador <- 1
    
    enquanto (contador <= 4) faca
             escreval()
             escreva("Quanto Dinheiro tenho R$")
             leia(Reais)
             dolar <-  Reais/2.20
             escreval()
             escreval("O valor de R$",Reais, " dara Us$", dolar:6:2)
             contador <- contador + 1
    fimenquanto


Fimalgoritmo