Algoritmo "melhoraluno"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 22/05/2020
Var
// Seção de Declarações das variáveis 


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
//
//Quantidade de alunos

// pede nome e nota
//pede a nota
//

//Mostra qual é nome e nota do melhor aluno

Fimalgoritmo