Algoritmo "utilizadorEscolheContagem"

Var
   valor, contador, salto : inteiro


Inicio
    escreva("Deseja contar até quanto? ")
    leia(valor)
    escreva("Qual o valor da contagem? ")
    leia(salto)

    contador <- 0
    escreval()
    enquanto (contador <= valor) faca
       escreval(contador)
       contador <- contador + salto
    fimenquanto
    
    escreval()
    escreval("Terminei de contar!")

Fimalgoritmo